This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./diff.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file diff.acn.....done (1174 entries accepted, 0 rejected).
Sorting entries............done (13425 comparisons).
Generating output file diff.acr....done (399 lines written, 0 warnings).
Output written in diff.acr.
Transcript written in diff.alg.
